import { randomUUID } from 'node:crypto';
import { DataSource, QueryRunner } from 'typeorm';
import { EnforceUserIdentifierUniqueness20260927000003 } from './20260927000003-enforce-user-identifier-uniqueness';

const runWithPostgres =
  process.env.CI === 'true' && process.env.DB_HOST ? describe : describe.skip;

runWithPostgres('user identifier migration (PostgreSQL)', () => {
  let admin: DataSource;
  let schema: string;
  let migrationRunner: QueryRunner;
  let clients: QueryRunner[];

  beforeAll(async () => {
    admin = new DataSource({
      type: 'postgres',
      host: process.env.DB_HOST,
      port: Number(process.env.DB_PORT ?? 5432),
      username: process.env.DB_USERNAME,
      password: process.env.DB_PASSWORD,
      database: process.env.DB_NAME,
      entities: [],
      synchronize: false,
    });
    await admin.initialize();
  });

  beforeEach(async () => {
    schema = `unique_${randomUUID().replace(/-/g, '')}`;
    await admin.query(`CREATE SCHEMA "${schema}"`);
    migrationRunner = admin.createQueryRunner();
    await migrationRunner.connect();
    await migrationRunner.query(`SET search_path TO "${schema}"`);
    await migrationRunner.query(`
      CREATE TABLE "user" (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username text NOT NULL,
        email_hash text NOT NULL
      )
    `);
    clients = [];
  });

  afterEach(async () => {
    for (const client of clients) await client.release();
    if (migrationRunner?.isReleased === false) await migrationRunner.release();
    await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
  });

  afterAll(async () => {
    if (admin?.isInitialized) await admin.destroy();
  });

  it('enforces identifiers during concurrent inserts and rolls back its indexes', async () => {
    const migration = new EnforceUserIdentifierUniqueness20260927000003();
    await migration.up(migrationRunner);

    const insert = async (emailHash: string) => {
      const client = admin.createQueryRunner();
      clients.push(client);
      await client.connect();
      await client.query(`SET search_path TO "${schema}"`);
      return client.query(
        `INSERT INTO "user" (username, email_hash) VALUES ($1, $2)`,
        ['same-name', emailHash],
      );
    };

    const results = await Promise.allSettled([
      insert('email-a'),
      insert('email-b'),
    ]);
    expect(
      results.filter((result) => result.status === 'fulfilled'),
    ).toHaveLength(1);
    const rejected = results.find(
      (result) => result.status === 'rejected',
    ) as PromiseRejectedResult;
    expect((rejected.reason as { code?: string }).code).toBe('23505');

    await migration.down(migrationRunner);
    const remainingIndexes = await migrationRunner.query(
      `SELECT indexname FROM pg_indexes WHERE schemaname = $1 AND indexname IN ('UQ_user_username', 'UQ_user_email_hash')`,
      [schema],
    );
    expect(remainingIndexes).toEqual([]);
  });
});
